### PR TITLE
Automatic account feature parsing / refreshing from settings

### PR DESCRIPTION
**Pull request by Sereri**

### CODE REVIEW

**Comment by 2fast2fourier** [comment]
Looking pretty good! I know someone requested the volume key stuff a while ago, they'll be pretty happy.

**Comment by Sereri** [comment]
Currently only works on the webview. Scrolling the 2 listviews is possible but a lot more iffy.

**Comment by 2fast2fourier** [comment]
Hmm, a possible solution is to use listview's smoothScrollBy call with the result of Math.min(windowheight, listview.getHeight()-getScrollY()). Then it should scroll by a whole screen until it's near the bottom, then scroll only the remaining distance.

Pull to refresh could possibly mess this up a bit, it's views might contribute to the total height.

e: You'll need to change that calculation for the upwards scroll to just Math.min(windowheight, getScrollY())

**Comment by Sereri** [comment]
I went with this:
https://github.com/Sereri/Something-Awful-Android/commit/f84098f80c3782a202918da97b440f8db652e91c
Works well enough, however if you enter the app and press the bookmark button ( not the list entry) the forums index still has the focus and the threads won't scroll.

**Comment by Sereri** [comment]
Also this requires the min API to be raised to 8 from 7. Though I'd be fine with that. Fuck eclair.

**Pull request merged**
